#!/usr/bin/env python3
"""
Sprite Library - Generated by scene_editor
"""

import pyunicodegame


# Sprite definitions for editor reload and runtime use
SPRITE_DEFS = {
    'c1': {
        'width': 2,
        'height': 1,
        'default_fg': (255, 255, 255),
        'frames': [
            {
                'chars': [
                    ['🩅', ' '],
                ],
                'fg_colors': [
                    [None, None],
                ],
            },
            {
                'chars': [
                    ['🨷', ' '],
                ],
                'fg_colors': [
                    [None, None],
                ],
            },
        ],
    },
}


def create_sprite(name: str, x: int, y: int):
    """Create a pyunicodegame sprite from definition."""
    defn = SPRITE_DEFS[name]
    frame = defn['frames'][0]
    pattern = '\n'.join(''.join(row) for row in frame['chars'])
    sprite = pyunicodegame.create_sprite(pattern, x, y, fg=defn['default_fg'])
    # Add additional frames if present
    for f in defn['frames'][1:]:
        pattern = '\n'.join(''.join(row) for row in f['chars'])
        sprite.add_frame(pattern)
    return sprite


def main():
    """Demo: display the sprite"""
    root = pyunicodegame.init(
        "Sprite: c1",
        width=20,
        height=10,
        bg=(10, 10, 20, 255)
    )

    sprite = create_sprite('c1', 2, 2)
    root.add_sprite(sprite)

    def on_key(key):
        import pygame
        if key == pygame.K_q:
            pyunicodegame.quit()

    pyunicodegame.run(on_key=on_key)


if __name__ == "__main__":
    main()
