#!/usr/bin/env python3
"""
Sprite Library - Generated by scene_editor
"""

import pyunicodegame


# Sprite definitions for editor reload and runtime use
SPRITE_DEFS = {
    'untitled': {
        'width': 8,
        'height': 6,
        'default_fg': (255, 255, 255),
        'frames': [
            {
                'chars': [
                    ['鿸', ' ', '鿷', ' ', '鿶', ' ', '鿵', ' '],
                    ['鿴', ' ', '鿳', ' ', '鿲', ' ', '鿱', ' '],
                    ['鿰', ' ', '鿯', ' ', '鿮', ' ', '鿭', ' '],
                    ['鿬', ' ', '鿫', ' ', '鿪', ' ', '鿩', ' '],
                    ['鿨', ' ', '鿧', ' ', '鿦', ' ', '鿥', ' '],
                    ['鿤', ' ', '鿣', ' ', '鿢', ' ', '鿡', ' '],
                ],
                'fg_colors': [
                    [None, None, None, None, None, None, None, None],
                    [None, None, None, None, None, None, None, None],
                    [None, None, None, None, None, None, None, None],
                    [None, None, None, None, None, None, None, None],
                    [None, None, None, None, None, None, None, None],
                    [None, None, None, None, None, None, None, None],
                ],
            },
        ],
    },
}


def create_sprite(name: str, x: int, y: int):
    """Create a pyunicodegame sprite from definition."""
    defn = SPRITE_DEFS[name]
    frame = defn['frames'][0]
    pattern = '\n'.join(''.join(row) for row in frame['chars'])
    sprite = pyunicodegame.create_sprite(pattern, x, y, fg=defn['default_fg'])
    # Add additional frames if present
    for f in defn['frames'][1:]:
        pattern = '\n'.join(''.join(row) for row in f['chars'])
        sprite.add_frame(pattern)
    return sprite


def main():
    """Demo: display the sprite"""
    root = pyunicodegame.init(
        "Sprite: untitled",
        width=20,
        height=10,
        bg=(10, 10, 20, 255)
    )

    sprite = create_sprite('untitled', 2, 2)
    root.add_sprite(sprite)

    def on_key(key):
        import pygame
        if key == pygame.K_q:
            pyunicodegame.quit()

    pyunicodegame.run(on_key=on_key)


if __name__ == "__main__":
    main()
