#!/usr/bin/env python3
"""
Scene: pndscene.py - Generated by scene_editor
"""

import pygame
import pyunicodegame

# Sprite library imports
from pnd import SPRITE_DEFS as pnd_SPRITES


def render_scene(window):
    """Render static character placements to the scene"""
    pass  # No static characters


def create_scene_sprites(window):
    """Create and position sprite instances in the scene"""
    sprites = {}

    # untitled_001
    sprites['untitled_001'] = pyunicodegame.Sprite(
        pnd_SPRITES['untitled'],
        0, 0
    )
    window.add_sprite(sprites['untitled_001'])

    # untitled_002
    sprites['untitled_002'] = pyunicodegame.Sprite(
        pnd_SPRITES['untitled'],
        0, 1
    )
    window.add_sprite(sprites['untitled_002'])

    # untitled_003
    sprites['untitled_003'] = pyunicodegame.Sprite(
        pnd_SPRITES['untitled'],
        2, 1
    )
    window.add_sprite(sprites['untitled_003'])

    # untitled_004
    sprites['untitled_004'] = pyunicodegame.Sprite(
        pnd_SPRITES['untitled'],
        2, 0
    )
    window.add_sprite(sprites['untitled_004'])

    return sprites


def main():
    root = pyunicodegame.init(
        "Scene",
        width=60,
        height=21,
        bg=(10, 10, 20, 255)
    )

    sprites = create_scene_sprites(root)

    def render():
        render_scene(root)

    def update(dt):
        root.update_sprites(dt)

    def on_key(key):
        if key == pygame.K_q:
            pyunicodegame.quit()

    pyunicodegame.run(render=render, update=update, on_key=on_key)


# Scene metadata for editor reload
_SCENE_META = {
    'width': 60,
    'height': 21,
    'char_placements': {
    },
    'sprite_instances': {
        'untitled_001': {
            'library_key': 'pnd.py:untitled',
            'x': 0,
            'y': 0,
            'initial_animation': None,
        },
        'untitled_002': {
            'library_key': 'pnd.py:untitled',
            'x': 0,
            'y': 1,
            'initial_animation': None,
        },
        'untitled_003': {
            'library_key': 'pnd.py:untitled',
            'x': 2,
            'y': 1,
            'initial_animation': None,
        },
        'untitled_004': {
            'library_key': 'pnd.py:untitled',
            'x': 2,
            'y': 0,
            'initial_animation': None,
        },
    },
    'sprite_library': [
        'pnd.py',
    ],
}


if __name__ == "__main__":
    main()
