#!/usr/bin/env python3
"""
Scene: yendor.py - Generated by scene_editor
"""

import pygame
import pyunicodegame

# Sprite library imports
from staff import SPRITE_DEFS as staff_SPRITES, create_sprite as staff_create_sprite


def render_scene(window):
    """Render static character placements to the scene"""
    # Row 1: "It is said that there is magic"
    window.put(15, 1, '𝐈', (255, 255, 255))
    window.put(16, 1, '𝐭', (255, 255, 255))
    window.put(18, 1, '𝐢', (255, 255, 255))
    window.put(19, 1, '𝐬', (255, 255, 255))
    window.put(21, 1, '𝐬', (255, 255, 255))
    window.put(22, 1, '𝐚', (255, 255, 255))
    window.put(23, 1, '𝐢', (255, 255, 255))
    window.put(24, 1, '𝐝', (255, 255, 255))
    window.put(26, 1, '𝐭', (255, 255, 255))
    window.put(27, 1, '𝐡', (255, 255, 255))
    window.put(28, 1, '𝐚', (255, 255, 255))
    window.put(29, 1, '𝐭', (255, 255, 255))
    window.put(31, 1, '𝐭', (255, 255, 255))
    window.put(32, 1, '𝐡', (255, 255, 255))
    window.put(33, 1, '𝐞', (255, 255, 255))
    window.put(34, 1, '𝐫', (255, 255, 255))
    window.put(35, 1, '𝐞', (255, 255, 255))
    window.put(37, 1, '𝐢', (255, 255, 255))
    window.put(38, 1, '𝐬', (255, 255, 255))
    window.put(40, 1, '𝓜', (255, 255, 255))
    window.put(41, 1, '𝓪', (255, 255, 255))
    window.put(42, 1, '𝓰', (255, 255, 255))
    window.put(43, 1, '𝓲', (255, 255, 255))
    window.put(44, 1, '𝓬', (255, 255, 255))
    # Row 2: "Contained within the staff of Yendor"
    window.put(12, 2, '𝐂', (255, 255, 255))
    window.put(13, 2, '𝐨', (255, 255, 255))
    window.put(14, 2, '𝐧', (255, 255, 255))
    window.put(15, 2, '𝐭', (255, 255, 255))
    window.put(16, 2, '𝐚', (255, 255, 255))
    window.put(17, 2, '𝐢', (255, 255, 255))
    window.put(18, 2, '𝐧', (255, 255, 255))
    window.put(19, 2, '𝐞', (255, 255, 255))
    window.put(20, 2, '𝐝', (255, 255, 255))
    window.put(22, 2, '𝐰', (255, 255, 255))
    window.put(23, 2, '𝐢', (255, 255, 255))
    window.put(24, 2, '𝐭', (255, 255, 255))
    window.put(25, 2, '𝐡', (255, 255, 255))
    window.put(26, 2, '𝐢', (255, 255, 255))
    window.put(27, 2, '𝐧', (255, 255, 255))
    window.put(29, 2, '𝐭', (255, 255, 255))
    window.put(30, 2, '𝐡', (255, 255, 255))
    window.put(31, 2, '𝐞', (255, 255, 255))
    window.put(33, 2, '𝓢', (255, 255, 255))
    window.put(34, 2, '𝓽', (255, 255, 255))
    window.put(35, 2, '𝓪', (255, 255, 255))
    window.put(36, 2, '𝓯', (255, 255, 255))
    window.put(37, 2, '𝓯', (255, 255, 255))
    window.put(39, 2, '𝓸', (255, 255, 255))
    window.put(40, 2, '𝓯', (255, 255, 255))
    window.put(42, 2, '𝓨', (255, 255, 255))
    window.put(43, 2, '𝓮', (255, 255, 255))
    window.put(44, 2, '𝓷', (255, 255, 255))
    window.put(45, 2, '𝓭', (255, 255, 255))
    window.put(46, 2, '𝓸', (255, 255, 255))
    window.put(47, 2, '𝓻', (255, 255, 255))
    # Row 18: "Which has the power to recommend Reason"
    window.put(10, 18, '𝐖', (255, 255, 255))
    window.put(11, 18, '𝐡', (255, 255, 255))
    window.put(12, 18, '𝐢', (255, 255, 255))
    window.put(13, 18, '𝐜', (255, 255, 255))
    window.put(14, 18, '𝐡', (255, 255, 255))
    window.put(16, 18, '𝐡', (255, 255, 255))
    window.put(17, 18, '𝐚', (255, 255, 255))
    window.put(18, 18, '𝐬', (255, 255, 255))
    window.put(20, 18, '𝐭', (255, 255, 255))
    window.put(21, 18, '𝐡', (255, 255, 255))
    window.put(22, 18, '𝐞', (255, 255, 255))
    window.put(24, 18, '𝐩', (255, 255, 255))
    window.put(25, 18, '𝐨', (255, 255, 255))
    window.put(26, 18, '𝐰', (255, 255, 255))
    window.put(27, 18, '𝐞', (255, 255, 255))
    window.put(28, 18, '𝐫', (255, 255, 255))
    window.put(30, 18, '𝐭', (255, 255, 255))
    window.put(31, 18, '𝐨', (255, 255, 255))
    window.put(33, 18, '𝐫', (255, 255, 255))
    window.put(34, 18, '𝐞', (255, 255, 255))
    window.put(35, 18, '𝐜', (255, 255, 255))
    window.put(36, 18, '𝐨', (255, 255, 255))
    window.put(37, 18, '𝐦', (255, 255, 255))
    window.put(38, 18, '𝐦', (255, 255, 255))
    window.put(39, 18, '𝐞', (255, 255, 255))
    window.put(40, 18, '𝐧', (255, 255, 255))
    window.put(41, 18, '𝐝', (255, 255, 255))
    window.put(43, 18, '𝓡', (255, 255, 255))
    window.put(44, 18, '𝓮', (255, 255, 255))
    window.put(45, 18, '𝓪', (255, 255, 255))
    window.put(46, 18, '𝓼', (255, 255, 255))
    window.put(47, 18, '𝓸', (255, 255, 255))
    window.put(48, 18, '𝓷', (255, 255, 255))
    # Row 19: "To a dark and truthless world"
    window.put(15, 19, '𝐓', (255, 255, 255))
    window.put(16, 19, '𝐨', (255, 255, 255))
    window.put(18, 19, '𝐚', (255, 255, 255))
    window.put(20, 19, '𝐝', (255, 255, 255))
    window.put(21, 19, '𝐚', (255, 255, 255))
    window.put(22, 19, '𝐫', (255, 255, 255))
    window.put(23, 19, '𝐤', (255, 255, 255))
    window.put(25, 19, '𝐚', (255, 255, 255))
    window.put(26, 19, '𝐧', (255, 255, 255))
    window.put(27, 19, '𝐝', (255, 255, 255))
    window.put(29, 19, '𝐭', (255, 255, 255))
    window.put(30, 19, '𝐫', (255, 255, 255))
    window.put(31, 19, '𝐮', (255, 255, 255))
    window.put(32, 19, '𝐭', (255, 255, 255))
    window.put(33, 19, '𝐡', (255, 255, 255))
    window.put(34, 19, '𝐥', (255, 255, 255))
    window.put(35, 19, '𝐞', (255, 255, 255))
    window.put(36, 19, '𝐬', (255, 255, 255))
    window.put(37, 19, '𝐬', (255, 255, 255))
    window.put(39, 19, '𝐰', (255, 255, 255))
    window.put(40, 19, '𝐨', (255, 255, 255))
    window.put(41, 19, '𝐫', (255, 255, 255))
    window.put(42, 19, '𝐥', (255, 255, 255))
    window.put(43, 19, '𝐝', (255, 255, 255))


def create_scene_sprites(window):
    """Create and position sprite instances in the scene"""
    sprites = {}

    # yendor_002
    sprites['yendor_002'] = staff_create_sprite('yendor', 27, 3)
    window.add_sprite(sprites['yendor_002'])

    return sprites


def main():
    root = pyunicodegame.init(
        "Scene",
        width=60,
        height=21,
        bg=(10, 10, 20, 255)
    )

    sprites = create_scene_sprites(root)

    def render():
        render_scene(root)

    def update(dt):
        root.update_sprites(dt)

    def on_key(key):
        if key == pygame.K_q:
            pyunicodegame.quit()

    pyunicodegame.run(render=render, update=update, on_key=on_key)


# Scene metadata for editor reload
_SCENE_META = {
    'width': 60,
    'height': 21,
    'char_placements': {
        # Row 1: "It is said that there is magic"
        (15, 1): {'char': '𝐈', 'fg': [255, 255, 255], 'bg': None},
        (16, 1): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (18, 1): {'char': '𝐢', 'fg': [255, 255, 255], 'bg': None},
        (19, 1): {'char': '𝐬', 'fg': [255, 255, 255], 'bg': None},
        (21, 1): {'char': '𝐬', 'fg': [255, 255, 255], 'bg': None},
        (22, 1): {'char': '𝐚', 'fg': [255, 255, 255], 'bg': None},
        (23, 1): {'char': '𝐢', 'fg': [255, 255, 255], 'bg': None},
        (24, 1): {'char': '𝐝', 'fg': [255, 255, 255], 'bg': None},
        (26, 1): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (27, 1): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (28, 1): {'char': '𝐚', 'fg': [255, 255, 255], 'bg': None},
        (29, 1): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (31, 1): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (32, 1): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (33, 1): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (34, 1): {'char': '𝐫', 'fg': [255, 255, 255], 'bg': None},
        (35, 1): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (37, 1): {'char': '𝐢', 'fg': [255, 255, 255], 'bg': None},
        (38, 1): {'char': '𝐬', 'fg': [255, 255, 255], 'bg': None},
        (40, 1): {'char': '𝓜', 'fg': [255, 255, 255], 'bg': None},
        (41, 1): {'char': '𝓪', 'fg': [255, 255, 255], 'bg': None},
        (42, 1): {'char': '𝓰', 'fg': [255, 255, 255], 'bg': None},
        (43, 1): {'char': '𝓲', 'fg': [255, 255, 255], 'bg': None},
        (44, 1): {'char': '𝓬', 'fg': [255, 255, 255], 'bg': None},
        # Row 2: "Contained within the staff of Yendor"
        (12, 2): {'char': '𝐂', 'fg': [255, 255, 255], 'bg': None},
        (13, 2): {'char': '𝐨', 'fg': [255, 255, 255], 'bg': None},
        (14, 2): {'char': '𝐧', 'fg': [255, 255, 255], 'bg': None},
        (15, 2): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (16, 2): {'char': '𝐚', 'fg': [255, 255, 255], 'bg': None},
        (17, 2): {'char': '𝐢', 'fg': [255, 255, 255], 'bg': None},
        (18, 2): {'char': '𝐧', 'fg': [255, 255, 255], 'bg': None},
        (19, 2): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (20, 2): {'char': '𝐝', 'fg': [255, 255, 255], 'bg': None},
        (22, 2): {'char': '𝐰', 'fg': [255, 255, 255], 'bg': None},
        (23, 2): {'char': '𝐢', 'fg': [255, 255, 255], 'bg': None},
        (24, 2): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (25, 2): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (26, 2): {'char': '𝐢', 'fg': [255, 255, 255], 'bg': None},
        (27, 2): {'char': '𝐧', 'fg': [255, 255, 255], 'bg': None},
        (29, 2): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (30, 2): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (31, 2): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (33, 2): {'char': '𝓢', 'fg': [255, 255, 255], 'bg': None},
        (34, 2): {'char': '𝓽', 'fg': [255, 255, 255], 'bg': None},
        (35, 2): {'char': '𝓪', 'fg': [255, 255, 255], 'bg': None},
        (36, 2): {'char': '𝓯', 'fg': [255, 255, 255], 'bg': None},
        (37, 2): {'char': '𝓯', 'fg': [255, 255, 255], 'bg': None},
        (39, 2): {'char': '𝓸', 'fg': [255, 255, 255], 'bg': None},
        (40, 2): {'char': '𝓯', 'fg': [255, 255, 255], 'bg': None},
        (42, 2): {'char': '𝓨', 'fg': [255, 255, 255], 'bg': None},
        (43, 2): {'char': '𝓮', 'fg': [255, 255, 255], 'bg': None},
        (44, 2): {'char': '𝓷', 'fg': [255, 255, 255], 'bg': None},
        (45, 2): {'char': '𝓭', 'fg': [255, 255, 255], 'bg': None},
        (46, 2): {'char': '𝓸', 'fg': [255, 255, 255], 'bg': None},
        (47, 2): {'char': '𝓻', 'fg': [255, 255, 255], 'bg': None},
        # Row 18: "Which has the power to recommend Reason"
        (10, 18): {'char': '𝐖', 'fg': [255, 255, 255], 'bg': None},
        (11, 18): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (12, 18): {'char': '𝐢', 'fg': [255, 255, 255], 'bg': None},
        (13, 18): {'char': '𝐜', 'fg': [255, 255, 255], 'bg': None},
        (14, 18): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (16, 18): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (17, 18): {'char': '𝐚', 'fg': [255, 255, 255], 'bg': None},
        (18, 18): {'char': '𝐬', 'fg': [255, 255, 255], 'bg': None},
        (20, 18): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (21, 18): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (22, 18): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (24, 18): {'char': '𝐩', 'fg': [255, 255, 255], 'bg': None},
        (25, 18): {'char': '𝐨', 'fg': [255, 255, 255], 'bg': None},
        (26, 18): {'char': '𝐰', 'fg': [255, 255, 255], 'bg': None},
        (27, 18): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (28, 18): {'char': '𝐫', 'fg': [255, 255, 255], 'bg': None},
        (30, 18): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (31, 18): {'char': '𝐨', 'fg': [255, 255, 255], 'bg': None},
        (33, 18): {'char': '𝐫', 'fg': [255, 255, 255], 'bg': None},
        (34, 18): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (35, 18): {'char': '𝐜', 'fg': [255, 255, 255], 'bg': None},
        (36, 18): {'char': '𝐨', 'fg': [255, 255, 255], 'bg': None},
        (37, 18): {'char': '𝐦', 'fg': [255, 255, 255], 'bg': None},
        (38, 18): {'char': '𝐦', 'fg': [255, 255, 255], 'bg': None},
        (39, 18): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (40, 18): {'char': '𝐧', 'fg': [255, 255, 255], 'bg': None},
        (41, 18): {'char': '𝐝', 'fg': [255, 255, 255], 'bg': None},
        (43, 18): {'char': '𝓡', 'fg': [255, 255, 255], 'bg': None},
        (44, 18): {'char': '𝓮', 'fg': [255, 255, 255], 'bg': None},
        (45, 18): {'char': '𝓪', 'fg': [255, 255, 255], 'bg': None},
        (46, 18): {'char': '𝓼', 'fg': [255, 255, 255], 'bg': None},
        (47, 18): {'char': '𝓸', 'fg': [255, 255, 255], 'bg': None},
        (48, 18): {'char': '𝓷', 'fg': [255, 255, 255], 'bg': None},
        # Row 19: "To a dark and truthless world"
        (15, 19): {'char': '𝐓', 'fg': [255, 255, 255], 'bg': None},
        (16, 19): {'char': '𝐨', 'fg': [255, 255, 255], 'bg': None},
        (18, 19): {'char': '𝐚', 'fg': [255, 255, 255], 'bg': None},
        (20, 19): {'char': '𝐝', 'fg': [255, 255, 255], 'bg': None},
        (21, 19): {'char': '𝐚', 'fg': [255, 255, 255], 'bg': None},
        (22, 19): {'char': '𝐫', 'fg': [255, 255, 255], 'bg': None},
        (23, 19): {'char': '𝐤', 'fg': [255, 255, 255], 'bg': None},
        (25, 19): {'char': '𝐚', 'fg': [255, 255, 255], 'bg': None},
        (26, 19): {'char': '𝐧', 'fg': [255, 255, 255], 'bg': None},
        (27, 19): {'char': '𝐝', 'fg': [255, 255, 255], 'bg': None},
        (29, 19): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (30, 19): {'char': '𝐫', 'fg': [255, 255, 255], 'bg': None},
        (31, 19): {'char': '𝐮', 'fg': [255, 255, 255], 'bg': None},
        (32, 19): {'char': '𝐭', 'fg': [255, 255, 255], 'bg': None},
        (33, 19): {'char': '𝐡', 'fg': [255, 255, 255], 'bg': None},
        (34, 19): {'char': '𝐥', 'fg': [255, 255, 255], 'bg': None},
        (35, 19): {'char': '𝐞', 'fg': [255, 255, 255], 'bg': None},
        (36, 19): {'char': '𝐬', 'fg': [255, 255, 255], 'bg': None},
        (37, 19): {'char': '𝐬', 'fg': [255, 255, 255], 'bg': None},
        (39, 19): {'char': '𝐰', 'fg': [255, 255, 255], 'bg': None},
        (40, 19): {'char': '𝐨', 'fg': [255, 255, 255], 'bg': None},
        (41, 19): {'char': '𝐫', 'fg': [255, 255, 255], 'bg': None},
        (42, 19): {'char': '𝐥', 'fg': [255, 255, 255], 'bg': None},
        (43, 19): {'char': '𝐝', 'fg': [255, 255, 255], 'bg': None},
    },
    'sprite_instances': {
        'yendor_002': {
            'library_key': 'staff.py:yendor',
            'x': 27,
            'y': 3,
            'initial_animation': None,
        },
    },
    'sprite_library': [
        'staff.py',
    ],
}


if __name__ == "__main__":
    main()
